version: "3.3"

services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - nifi-network      
   
  nifi:
    build: .
    image: 'nifi'
    tty: true
    stdin_open: true
    privileged: true
    ports:
      - "8240-8249:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    networks:
      - nifi-network      
      
  registry:
    image: apache/nifi-registry:latest
    ports:
      - 18080:18080   
    networks:
      - nifi-network      

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo_nifi
    networks:
      - nifi-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 18980:8080        
    networks:
      - nifi-network           

networks: 
  nifi-network:
    driver: bridge